codecov:
  branch:
    master
    develop
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 4
  round: down
  range: "60...95"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
ignore:
    - /src/main/java/practice/entity/*.java
    - /src/main/java/practice/Application.java

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
