language: java
jdk:
- oraclejdk8
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
branches:
  only:
  - master
  - develop
script:
  - mvn clean compile -B -e -U
  - mvn test
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
    #deploy job here
